import '../models/track.dart';
import '../models/artist.dart';
import '../models/video.dart';
import '../models/product.dart';
import '../models/message.dart';
import '../models/conversation.dart';

/// Service providing mock data for MVP development
class MockDataService {
  MockDataService._(); // Private constructor to prevent instantiation

  /// Get mock music tracks
  static List<Track> getMockTracks() {
    return [
      Track(
        id: 'track1',
        title: 'Midnight Dreams',
        artistName: 'Luna Echo',
        artistId: 'artist1',
        coverUrl: 'https://picsum.photos/seed/track1/400',
        audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
        duration: const Duration(minutes: 3, seconds: 45),
        albumName: 'Nocturnal',
        likes: 1250,
        plays: 45000,
        genres: ['Electronic', 'Ambient'],
      ),
      Track(
        id: 'track2',
        title: 'Summer Vibes',
        artistName: 'The Coastal Crew',
        artistId: 'artist2',
        coverUrl: 'https://picsum.photos/seed/track2/400',
        audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
        duration: const Duration(minutes: 4, seconds: 12),
        albumName: 'Beach Days',
        likes: 2340,
        plays: 78000,
        genres: ['Pop', 'Indie'],
      ),
      Track(
        id: 'track3',
        title: 'Electric Storm',
        artistName: 'Neon Pulse',
        artistId: 'artist3',
        coverUrl: 'https://picsum.photos/seed/track3/400',
        audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
        duration: const Duration(minutes: 5, seconds: 20),
        likes: 890,
        plays: 32000,
        genres: ['EDM', 'House'],
      ),
      Track(
        id: 'track4',
        title: 'Sunset Boulevard',
        artistName: 'Jazz Collective',
        artistId: 'artist4',
        coverUrl: 'https://picsum.photos/seed/track4/400',
        audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
        duration: const Duration(minutes: 6, seconds: 5),
        albumName: 'City Lights',
        likes: 3200,
        plays: 120000,
        genres: ['Jazz', 'Smooth Jazz'],
      ),
      Track(
        id: 'track5',
        title: 'Broken Hearts Club',
        artistName: 'Sarah Rivers',
        artistId: 'artist5',
        coverUrl: 'https://picsum.photos/seed/track5/400',
        audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
        duration: const Duration(minutes: 3, seconds: 30),
        albumName: 'Vulnerable',
        likes: 5600,
        plays: 250000,
        genres: ['Pop', 'Ballad'],
      ),
      Track(
        id: 'track6',
        title: 'Wild Fire',
        artistName: 'The Mavericks',
        artistId: 'artist6',
        coverUrl: 'https://picsum.photos/seed/track6/400',
        audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
        duration: const Duration(minutes: 4, seconds: 45),
        likes: 1800,
        plays: 67000,
        genres: ['Rock', 'Alternative'],
      ),
      Track(
        id: 'track7',
        title: 'Tokyo Nights',
        artistName: 'Cyber Dreams',
        artistId: 'artist7',
        coverUrl: 'https://picsum.photos/seed/track7/400',
        audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
        duration: const Duration(minutes: 5, seconds: 10),
        albumName: 'Digital Paradise',
        likes: 2100,
        plays: 89000,
        genres: ['Synthwave', 'Electronic'],
      ),
      Track(
        id: 'track8',
        title: 'Mountain Echo',
        artistName: 'Folk Harmony',
        artistId: 'artist8',
        coverUrl: 'https://picsum.photos/seed/track8/400',
        audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
        duration: const Duration(minutes: 4, seconds: 28),
        likes: 950,
        plays: 41000,
        genres: ['Folk', 'Acoustic'],
      ),
      Track(
        id: 'track9',
        title: 'Bass Drop',
        artistName: 'DJ Thunder',
        artistId: 'artist9',
        coverUrl: 'https://picsum.photos/seed/track9/400',
        audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3',
        duration: const Duration(minutes: 3, seconds: 55),
        likes: 4200,
        plays: 180000,
        genres: ['Dubstep', 'Bass'],
      ),
      Track(
        id: 'track10',
        title: 'Classical Dreams',
        artistName: 'Orchestra Divine',
        artistId: 'artist10',
        coverUrl: 'https://picsum.photos/seed/track10/400',
        audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3',
        duration: const Duration(minutes: 7, seconds: 30),
        albumName: 'Symphonic Tales',
        likes: 1500,
        plays: 55000,
        genres: ['Classical', 'Orchestral'],
      ),
      Track(
        id: 'track11',
        title: 'Urban Jungle',
        artistName: 'Street Poets',
        artistId: 'artist11',
        coverUrl: 'https://picsum.photos/seed/track11/400',
        audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
        duration: const Duration(minutes: 3, seconds: 20),
        likes: 2800,
        plays: 95000,
        genres: ['Hip Hop', 'Rap'],
      ),
      Track(
        id: 'track12',
        title: 'Ocean Waves',
        artistName: 'Chill Masters',
        artistId: 'artist12',
        coverUrl: 'https://picsum.photos/seed/track12/400',
        audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
        duration: const Duration(minutes: 6, seconds: 15),
        albumName: 'Relaxation Zone',
        likes: 3400,
        plays: 140000,
        genres: ['Ambient', 'Chill'],
      ),
      Track(
        id: 'track13',
        title: 'Dance Revolution',
        artistName: 'Party Animals',
        artistId: 'artist13',
        coverUrl: 'https://picsum.photos/seed/track13/400',
        audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
        duration: const Duration(minutes: 4, seconds: 5),
        likes: 5100,
        plays: 220000,
        genres: ['Dance', 'Pop'],
      ),
      Track(
        id: 'track14',
        title: 'Autumn Leaves',
        artistName: 'Indie Soul',
        artistId: 'artist14',
        coverUrl: 'https://picsum.photos/seed/track14/400',
        audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
        duration: const Duration(minutes: 4, seconds: 50),
        likes: 1650,
        plays: 61000,
        genres: ['Indie', 'Soul'],
      ),
      Track(
        id: 'track15',
        title: 'Neon Lights',
        artistName: 'Future Bass',
        artistId: 'artist15',
        coverUrl: 'https://picsum.photos/seed/track15/400',
        audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
        duration: const Duration(minutes: 3, seconds: 40),
        albumName: 'Future Vibes',
        likes: 3900,
        plays: 165000,
        genres: ['Future Bass', 'Electronic'],
      ),
      Track(
        id: 'track16',
        title: 'Desert Wind',
        artistName: 'Nomad Sounds',
        artistId: 'artist16',
        coverUrl: 'https://picsum.photos/seed/track16/400',
        audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
        duration: const Duration(minutes: 5, seconds: 25),
        likes: 720,
        plays: 28000,
        genres: ['World', 'Ambient'],
      ),
      Track(
        id: 'track17',
        title: 'Midnight Rain',
        artistName: 'Lo-Fi Beats',
        artistId: 'artist17',
        coverUrl: 'https://picsum.photos/seed/track17/400',
        audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
        duration: const Duration(minutes: 4, seconds: 0),
        likes: 6200,
        plays: 310000,
        genres: ['Lo-Fi', 'Hip Hop'],
      ),
      Track(
        id: 'track18',
        title: 'Guitar Hero',
        artistName: 'Rock Legends',
        artistId: 'artist18',
        coverUrl: 'https://picsum.photos/seed/track18/400',
        audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
        duration: const Duration(minutes: 5, seconds: 35),
        albumName: 'Greatest Hits',
        likes: 2500,
        plays: 98000,
        genres: ['Rock', 'Classic Rock'],
      ),
      Track(
        id: 'track19',
        title: 'Soulful Sunday',
        artistName: 'R&B Kings',
        artistId: 'artist19',
        coverUrl: 'https://picsum.photos/seed/track19/400',
        audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3',
        duration: const Duration(minutes: 4, seconds: 18),
        likes: 4700,
        plays: 195000,
        genres: ['R&B', 'Soul'],
      ),
      Track(
        id: 'track20',
        title: 'Space Odyssey',
        artistName: 'Cosmic Travelers',
        artistId: 'artist20',
        coverUrl: 'https://picsum.photos/seed/track20/400',
        audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3',
        duration: const Duration(minutes: 8, seconds: 0),
        albumName: 'Beyond Stars',
        likes: 1100,
        plays: 48000,
        genres: ['Progressive', 'Psychedelic'],
      ),
    ];
  }

  /// Get mock videos (live and archived)
  static List<Video> getMockVideos() {
    final now = DateTime.now();
    return [
      Video(
        id: 'video1',
        title: 'LIVE: Luna Echo - Midnight Dreams Performance',
        artistName: 'Luna Echo',
        artistId: 'artist1',
        thumbnailUrl: 'https://picsum.photos/seed/video1/640/360',
        videoUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
        type: VideoType.live,
        isLive: true,
        publishedAt: now,
        views: 1250,
        description: 'Live performance of our latest single!',
      ),
      Video(
        id: 'video2',
        title: 'Summer Vibes - Official Music Video',
        artistName: 'The Coastal Crew',
        artistId: 'artist2',
        thumbnailUrl: 'https://picsum.photos/seed/video2/640/360',
        videoUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
        type: VideoType.archived,
        isLive: false,
        publishedAt: now.subtract(const Duration(days: 3)),
        duration: const Duration(minutes: 4, seconds: 15),
        views: 45000,
        description: 'Official music video filmed at the beach',
      ),
      Video(
        id: 'video3',
        title: 'Behind the Scenes: Electric Storm Recording',
        artistName: 'Neon Pulse',
        artistId: 'artist3',
        thumbnailUrl: 'https://picsum.photos/seed/video3/640/360',
        videoUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
        type: VideoType.behindScenes,
        isLive: false,
        publishedAt: now.subtract(const Duration(days: 7)),
        duration: const Duration(minutes: 12, seconds: 30),
        views: 12000,
        description: 'Exclusive look at our studio recording process',
      ),
      Video(
        id: 'video4',
        title: 'LIVE: Jazz Collective - Late Night Session',
        artistName: 'Jazz Collective',
        artistId: 'artist4',
        thumbnailUrl: 'https://picsum.photos/seed/video4/640/360',
        videoUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
        type: VideoType.live,
        isLive: true,
        publishedAt: now.subtract(const Duration(minutes: 30)),
        views: 890,
      ),
      Video(
        id: 'video5',
        title: 'Broken Hearts Club - Acoustic Version',
        artistName: 'Sarah Rivers',
        artistId: 'artist5',
        thumbnailUrl: 'https://picsum.photos/seed/video5/640/360',
        videoUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
        type: VideoType.archived,
        isLive: false,
        publishedAt: now.subtract(const Duration(days: 14)),
        duration: const Duration(minutes: 3, seconds: 45),
        views: 98000,
        description: 'Stripped down acoustic performance',
      ),
      Video(
        id: 'video6',
        title: 'Wild Fire - Concert Highlights',
        artistName: 'The Mavericks',
        artistId: 'artist6',
        thumbnailUrl: 'https://picsum.photos/seed/video6/640/360',
        videoUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
        type: VideoType.archived,
        isLive: false,
        publishedAt: now.subtract(const Duration(days: 5)),
        duration: const Duration(minutes: 8, seconds: 20),
        views: 34000,
      ),
      Video(
        id: 'video7',
        title: 'Tokyo Nights - Visual Album',
        artistName: 'Cyber Dreams',
        artistId: 'artist7',
        thumbnailUrl: 'https://picsum.photos/seed/video7/640/360',
        videoUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
        type: VideoType.archived,
        isLive: false,
        publishedAt: now.subtract(const Duration(days: 30)),
        duration: const Duration(minutes: 45, seconds: 0),
        views: 150000,
        description: 'Full visual album experience',
      ),
      Video(
        id: 'video8',
        title: 'Studio Jam Session',
        artistName: 'Folk Harmony',
        artistId: 'artist8',
        thumbnailUrl: 'https://picsum.photos/seed/video8/640/360',
        videoUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
        type: VideoType.behindScenes,
        isLive: false,
        publishedAt: now.subtract(const Duration(days: 2)),
        duration: const Duration(minutes: 15, seconds: 10),
        views: 8500,
      ),
      Video(
        id: 'video9',
        title: 'LIVE: Bass Drop Festival Set',
        artistName: 'DJ Thunder',
        artistId: 'artist9',
        thumbnailUrl: 'https://picsum.photos/seed/video9/640/360',
        videoUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
        type: VideoType.archived,
        isLive: false,
        publishedAt: now.subtract(const Duration(days: 10)),
        duration: const Duration(minutes: 60, seconds: 0),
        views: 210000,
        description: 'Full festival performance',
      ),
      Video(
        id: 'video10',
        title: 'Orchestra Divine - Symphony Hall Concert',
        artistName: 'Orchestra Divine',
        artistId: 'artist10',
        thumbnailUrl: 'https://picsum.photos/seed/video10/640/360',
        videoUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
        type: VideoType.archived,
        isLive: false,
        publishedAt: now.subtract(const Duration(days: 60)),
        duration: const Duration(minutes: 90, seconds: 0),
        views: 67000,
      ),
    ];
  }

  /// Get mock merch products
  static List<Product> getMockProducts() {
    return [
      Product(
        id: 'product1',
        name: 'Nocturnal Vinyl LP',
        imageUrl: 'https://picsum.photos/seed/product1/400',
        price: 29.99,
        category: ProductCategory.vinyl,
        artistName: 'Luna Echo',
        artistId: 'artist1',
        stock: 50,
        description: 'Limited edition vinyl pressing of the Nocturnal album',
      ),
      Product(
        id: 'product2',
        name: 'Beach Days Tour T-Shirt',
        imageUrl: 'https://picsum.photos/seed/product2/400',
        price: 24.99,
        category: ProductCategory.tshirt,
        artistName: 'The Coastal Crew',
        artistId: 'artist2',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        stock: 120,
        description: '100% cotton tour t-shirt',
      ),
      Product(
        id: 'product3',
        name: 'Neon Pulse Hoodie',
        imageUrl: 'https://picsum.photos/seed/product3/400',
        price: 49.99,
        category: ProductCategory.hoodie,
        artistName: 'Neon Pulse',
        artistId: 'artist3',
        sizes: ['S', 'M', 'L', 'XL'],
        stock: 75,
        description: 'Premium quality hoodie with glow-in-the-dark print',
      ),
      Product(
        id: 'product4',
        name: 'City Lights Poster Set',
        imageUrl: 'https://picsum.photos/seed/product4/400',
        price: 19.99,
        category: ProductCategory.poster,
        artistName: 'Jazz Collective',
        artistId: 'artist4',
        stock: 200,
        description: 'Set of 3 high-quality art prints',
      ),
      Product(
        id: 'product5',
        name: 'Vulnerable Signed CD',
        imageUrl: 'https://picsum.photos/seed/product5/400',
        price: 15.99,
        category: ProductCategory.other,
        artistName: 'Sarah Rivers',
        artistId: 'artist5',
        stock: 30,
        description: 'Signed CD with exclusive booklet',
      ),
      Product(
        id: 'product6',
        name: 'The Mavericks Band T-Shirt',
        imageUrl: 'https://picsum.photos/seed/product6/400',
        price: 22.99,
        category: ProductCategory.tshirt,
        artistName: 'The Mavericks',
        artistId: 'artist6',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        stock: 90,
      ),
      Product(
        id: 'product7',
        name: 'Digital Paradise Vinyl',
        imageUrl: 'https://picsum.photos/seed/product7/400',
        price: 34.99,
        category: ProductCategory.vinyl,
        artistName: 'Cyber Dreams',
        artistId: 'artist7',
        stock: 40,
        description: 'Transparent purple vinyl with digital download',
      ),
      Product(
        id: 'product8',
        name: 'Folk Harmony Acoustic Pick Set',
        imageUrl: 'https://picsum.photos/seed/product8/400',
        price: 9.99,
        category: ProductCategory.accessories,
        artistName: 'Folk Harmony',
        artistId: 'artist8',
        stock: 150,
        description: 'Set of 5 custom guitar picks',
      ),
      Product(
        id: 'product9',
        name: 'DJ Thunder Festival Hoodie',
        imageUrl: 'https://picsum.photos/seed/product9/400',
        price: 54.99,
        category: ProductCategory.hoodie,
        artistName: 'DJ Thunder',
        artistId: 'artist9',
        sizes: ['M', 'L', 'XL', 'XXL'],
        stock: 60,
      ),
      Product(
        id: 'product10',
        name: 'Symphonic Tales Collector Box',
        imageUrl: 'https://picsum.photos/seed/product10/400',
        price: 79.99,
        category: ProductCategory.other,
        artistName: 'Orchestra Divine',
        artistId: 'artist10',
        stock: 25,
        description: 'Limited edition box set with 3 CDs and artwork',
      ),
      Product(
        id: 'product11',
        name: 'Street Poets Snapback',
        imageUrl: 'https://picsum.photos/seed/product11/400',
        price: 27.99,
        category: ProductCategory.accessories,
        artistName: 'Street Poets',
        artistId: 'artist11',
        stock: 80,
      ),
      Product(
        id: 'product12',
        name: 'Relaxation Zone Vinyl',
        imageUrl: 'https://picsum.photos/seed/product12/400',
        price: 31.99,
        category: ProductCategory.vinyl,
        artistName: 'Chill Masters',
        artistId: 'artist12',
        stock: 45,
      ),
      Product(
        id: 'product13',
        name: 'Party Animals Tour Tee',
        imageUrl: 'https://picsum.photos/seed/product13/400',
        price: 23.99,
        category: ProductCategory.tshirt,
        artistName: 'Party Animals',
        artistId: 'artist13',
        sizes: ['S', 'M', 'L', 'XL'],
        stock: 110,
      ),
      Product(
        id: 'product14',
        name: 'Indie Soul Poster',
        imageUrl: 'https://picsum.photos/seed/product14/400',
        price: 14.99,
        category: ProductCategory.poster,
        artistName: 'Indie Soul',
        artistId: 'artist14',
        stock: 180,
      ),
      Product(
        id: 'product15',
        name: 'Future Vibes Hoodie',
        imageUrl: 'https://picsum.photos/seed/product15/400',
        price: 52.99,
        category: ProductCategory.hoodie,
        artistName: 'Future Bass',
        artistId: 'artist15',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        stock: 65,
      ),
    ];
  }

  /// Get mock messages for a conversation
  static List<Message> getMockMessages(String artistId) {
    final now = DateTime.now();
    return [
      Message(
        id: 'msg1',
        text: 'Hey! Thanks for listening to my music!',
        senderId: artistId,
        senderName: 'Luna Echo',
        senderAvatar: 'https://picsum.photos/seed/artist1/200',
        timestamp: now.subtract(const Duration(hours: 2)),
        isArtist: true,
        isRead: true,
      ),
      Message(
        id: 'msg2',
        text: 'I love your new album! The production is amazing 🔥',
        senderId: 'user123',
        senderName: 'You',
        timestamp: now.subtract(const Duration(hours: 1, minutes: 45)),
        isArtist: false,
        isRead: true,
      ),
      Message(
        id: 'msg3',
        text: 'Thank you so much! We worked really hard on it. What\'s your favorite track?',
        senderId: artistId,
        senderName: 'Luna Echo',
        senderAvatar: 'https://picsum.photos/seed/artist1/200',
        timestamp: now.subtract(const Duration(hours: 1, minutes: 30)),
        isArtist: true,
        isRead: true,
      ),
      Message(
        id: 'msg4',
        text: 'Definitely "Midnight Dreams" - the synths are incredible!',
        senderId: 'user123',
        senderName: 'You',
        timestamp: now.subtract(const Duration(hours: 1, minutes: 20)),
        isArtist: false,
        isRead: true,
      ),
      Message(
        id: 'msg5',
        text: 'That one was special to make. Are you coming to our show next month?',
        senderId: artistId,
        senderName: 'Luna Echo',
        senderAvatar: 'https://picsum.photos/seed/artist1/200',
        timestamp: now.subtract(const Duration(minutes: 30)),
        isArtist: true,
        isRead: false,
      ),
    ];
  }

  /// Get mock conversations
  static List<Conversation> getMockConversations() {
    final now = DateTime.now();
    return [
      Conversation(
        id: 'conv1',
        artistId: 'artist1',
        artistName: 'Luna Echo',
        artistAvatar: 'https://picsum.photos/seed/artist1/200',
        lastMessage: Message(
          id: 'msg5',
          text: 'That one was special to make. Are you coming to our show next month?',
          senderId: 'artist1',
          senderName: 'Luna Echo',
          timestamp: now.subtract(const Duration(minutes: 30)),
          isArtist: true,
        ),
        unreadCount: 1,
        lastActivity: now.subtract(const Duration(minutes: 30)),
      ),
      Conversation(
        id: 'conv2',
        artistId: 'artist2',
        artistName: 'The Coastal Crew',
        artistAvatar: 'https://picsum.photos/seed/artist2/200',
        lastMessage: Message(
          id: 'msg10',
          text: 'See you at the beach!',
          senderId: 'user123',
          senderName: 'You',
          timestamp: now.subtract(const Duration(hours: 5)),
          isArtist: false,
        ),
        unreadCount: 0,
        lastActivity: now.subtract(const Duration(hours: 5)),
      ),
      Conversation(
        id: 'conv3',
        artistId: 'artist5',
        artistName: 'Sarah Rivers',
        artistAvatar: 'https://picsum.photos/seed/artist5/200',
        lastMessage: Message(
          id: 'msg15',
          text: 'Thank you for your support! ❤️',
          senderId: 'artist5',
          senderName: 'Sarah Rivers',
          timestamp: now.subtract(const Duration(days: 1)),
          isArtist: true,
        ),
        unreadCount: 0,
        lastActivity: now.subtract(const Duration(days: 1)),
      ),
    ];
  }

  /// Get mock artists
  static List<Artist> getMockArtists() {
    return [
      Artist(
        id: 'artist1',
        name: 'Luna Echo',
        bio: 'Electronic music producer creating ambient soundscapes',
        avatarUrl: 'https://picsum.photos/seed/artist1/200',
        coverUrl: 'https://picsum.photos/seed/artist1cover/800/300',
        followers: 45000,
        genres: ['Electronic', 'Ambient'],
      ),
      Artist(
        id: 'artist2',
        name: 'The Coastal Crew',
        bio: 'Indie pop band bringing summer vibes all year round',
        avatarUrl: 'https://picsum.photos/seed/artist2/200',
        coverUrl: 'https://picsum.photos/seed/artist2cover/800/300',
        followers: 78000,
        genres: ['Pop', 'Indie'],
      ),
      // Add more artists as needed
    ];
  }
}
